# This file was generated by GoReleaser. DO NOT EDIT.
cask "kite-collector" do
  version "0.57.0"

  on_macos do
    on_arm do
      sha256 "a2624f541708e8fe34caf64944e58dcf1bec3618ead2c830db4861865b0339e4"
      url "https://github.com/VulnerTrack/kite-collector/releases/download/v#{version}/kite-collector_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e3e96b2e40e51373c158c59258b345bdce6d3400fcdc2c5e934968232e9e5638"
      url "https://github.com/VulnerTrack/kite-collector/releases/download/v#{version}/kite-collector_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f23f1cc48d04371bf0a2d1bc6525fe40d679d2733b4a579fda16c2c49c9b10ea"
      url "https://github.com/VulnerTrack/kite-collector/releases/download/v#{version}/kite-collector_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9860228adcdd7c2acac61c97587f1490a1eaa4e28e76ed88ae0d8cf8f0023a14"
      url "https://github.com/VulnerTrack/kite-collector/releases/download/v#{version}/kite-collector_linux_amd64.tar.gz"
    end
  end

  name "kite-collector"
  desc "Cybersecurity machine discovery, configuration audit, and posture analysis agent"
  homepage "https://github.com/VulnerTrack/kite-collector"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kite-collector"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kite-collector"]
    end
  end

  uninstall launchctl: [
      "kite-collector",
    ]

  # No zap stanza required

  caveats <<~EOS
    To run kite-collector as a background service (registers a launchd
    daemon pointing at the brew-managed binary — brew upgrades restart
    the service automatically):
      sudo kite-collector install
    Before `brew uninstall`, remove the service registration:
      sudo kite-collector uninstall
  EOS
end
