# This file was generated by GoReleaser. DO NOT EDIT.
cask "kite-collector" do
  version "0.26.0"

  on_macos do
    on_intel do
      sha256 "079044324d0af62b05cb7b86c9aad4f1f275e579f7a17d2ea5efcfbcd42727c8"
      url "https://github.com/VulnerTrack/kite-collector/releases/download/v#{version}/kite-collector_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e534cb4430218f4a248b4f235d572c227aa1642ce8326b9e0a3f3d67e125d077"
      url "https://github.com/VulnerTrack/kite-collector/releases/download/v#{version}/kite-collector_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "83cf9bec3ce1130eaf0fe4a64fd828d3b9ce8772e7d9541df533c968ec9f3056"
      url "https://github.com/VulnerTrack/kite-collector/releases/download/v#{version}/kite-collector_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "120cbfd0f98c49547a942c0ceb6be3b0c815d12eb24ee2f720a42d62aa341d5a"
      url "https://github.com/VulnerTrack/kite-collector/releases/download/v#{version}/kite-collector_linux_arm64.tar.gz"
    end
  end

  name "kite-collector"
  desc "Cybersecurity asset discovery, configuration audit, and posture analysis agent"
  homepage "https://github.com/VulnerTrack/kite-collector"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kite-collector"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kite-collector"]
    end
  end

  # No zap stanza required

end
