# This file was generated by GoReleaser. DO NOT EDIT.
cask "kite-collector" do
  version "0.33.1"

  on_macos do
    on_intel do
      sha256 "ce006bb7727c2342c674f6e2928120210ebae2e4b49bc1ca8ef7583f6ef57355"
      url "https://github.com/VulnerTrack/kite-collector/releases/download/v#{version}/kite-collector_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bf0546b4b789790c3367254da422ad6acf054bf75d363a03ee5529363f149ec3"
      url "https://github.com/VulnerTrack/kite-collector/releases/download/v#{version}/kite-collector_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "00f060d03346cc9962f51c30454424df468e9d33399c27ef076004ef606a4dcd"
      url "https://github.com/VulnerTrack/kite-collector/releases/download/v#{version}/kite-collector_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2115c41b48b67b8806e090a6fa3d152380e852f37534c82f7c94a0639edc633d"
      url "https://github.com/VulnerTrack/kite-collector/releases/download/v#{version}/kite-collector_linux_arm64.tar.gz"
    end
  end

  name "kite-collector"
  desc "Cybersecurity asset discovery, configuration audit, and posture analysis agent"
  homepage "https://github.com/VulnerTrack/kite-collector"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kite-collector"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kite-collector"]
    end
  end

  # No zap stanza required

end
